# Generated by Django 2.1.3 on 2018-11-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='sentiment_confidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='document',
            name='sentiment_polarity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
